const ImagePath = {
  LOGO: "/IS-logo.webp",
  LOGO_WHITE: "/IS-Logo-White.webp",
  HERO_IMG: "/Athlete_Img.png",
  COGNIA_LOGO: "/cognia.logo.webp",
  COLLEGEBOARD_LOGO: "/college-board-logo.webp",
  NCAA_LOGO: "/ncaa-logo.webp",
  BOOK_ICON: "/book.svg",
  TEACHER_ICON: "/teacher-icon.svg",
  CURRICULUM_ICON: "/curriculum-icon.svg",
  CLASS_ICON: "/class-icon.svg",
  MEDAL_ICON: "/medal.svg",
  DOCTOR_ICON: "/doctor.svg",
  BRAIN_ICON: "/brain.svg",
  TIME_ICON: "/time.svg",
  HONORS_ICON: "/honors.svg",
  MAP_ICON: "/map.svg",
  PROFILE_ICON: "/profile.svg",
  GOOGLE_RATING: "/google.webp",
  TRUSTPILOT_RATING: "/trustpilot.webp",
  TESTIMONIALS_1: "/testimonial-1.webp",
  TESTIMONIALS_2: "/testimonial-2.webp",
  TESTIMONIALS_3: "/testimonial-3.webp",
  ABOUT_IMG: "/atheletes-cover.webp",
  VISOIN_ICON: "/vision_icon.svg",
  MISSION_ICON: "/mission_icon.svg",
  PHILOSOPHY_ICON: "/philosophy_icon.svg",
  ICON1: "/icon1.svg",
  ICON2: "/icon2.svg",
  ICON3: "/icon3.svg",
  ICON4: "/icon4.svg",
  WHY_US_IMG: "/why_img.webp",
  MAP_IMG: "/contact_map.png",
  CONTACT_IMG: "/contact.webp",
  APPROVED_BY_NCAA: "/approved.svg",
  ACCREDITED: "/seal_certificate.svg",
  AFFORDABLE: "/funding.svg",
  CUSTOMIZED_LEARNING: "/Customized_learning.svg",
  FLEXIBLE_STUDY: "/Flexible_Study_Hours.svg",
  FREE_COUNSELING: "/Councelling.svg",
  SUPPORT: "/24_ hours_support.svg",
  STUDENT_ATHLETE: "/Student_Athletes.svg",
  RATING: "/rating.png",
  RATING_GOOGLE: "/google.png",
  RATING_TRUSTPILOT: "/trustpilot.png",
  CHECK_ICON: "/check.svg",
  ATHLETE_HERO_IMAGE: "/Athlete_image.png",
  ADVANCED_LOGO: "/advancED.webp",
  SCHOLARSHIP_IMAGE: "/Scholarship_Image.png",
  BASKETBALL_PLAYER: "/Basketball_Player.webp",
  HORSE_JUMPER: "/Horse_Jumper .jpg",
  BASKETBALL_NEXT_PLAYER: "/next_Basketball.webp",
  FLEXIBILITY: "/Flexibility_icon.svg",
};
export default ImagePath;
